baseURL = "https://tamnd.github.io/brain/"
title = "brain"
theme = "hugo-book"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    label = "English"
    locale = "en-US"
    contentDir = "content/en"
    weight = 1

  [languages.zh]
    label = "中文"
    locale = "zh-CN"
    contentDir = "content/zh"
    weight = 2

  [languages.vi]
    label = "Tiếng Việt"
    locale = "vi"
    contentDir = "content/vi"
    weight = 3

  [languages.ja]
    label = "日本語"
    locale = "ja"
    contentDir = "content/ja"
    weight = 4

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookSection = "*"
  BookDateFormat = "2006-01-02"
  BookRepo = "https://github.com/tamnd/brain"
  BookEditPath = "edit/main/content"

[markup.goldmark.renderer]
  unsafe = true
